eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  
    service-url:
     defaultzone: http://localhost:8761/eureka        
  instance:
    hostname: localhost  
    
    
microservice:
  payment-service:
      endpoints:
        endpoint:
          uri: http://PAYMENTS-SERVICE/payment-provider/doPayment
  order-service:
      endpoints:
        endpoint:
          uri: http://SHOPPING-SERVICE/order/bookorder
